package reason

const (
	PrivilegeLevel1Desc = "privilege.level_1.description"
	PrivilegeLevel2Desc = "privilege.level_2.description"
	PrivilegeLevel3Desc = "privilege.level_3.description"

	RankQuestionAddLabel               = "privilege.rank_question_add_label"
	RankAnswerAddLabel                 = "privilege.rank_answer_add_label"
	RankCommentAddLabel                = "privilege.rank_comment_add_label"
	RankReportAddLabel                 = "privilege.rank_report_add_label"
	RankCommentVoteUpLabel             = "privilege.rank_comment_vote_up_label"
	RankLinkUrlLimitLabel              = "privilege.rank_link_url_limit_label"
	RankQuestionVoteUpLabel            = "privilege.rank_question_vote_up_label"
	RankAnswerVoteUpLabel              = "privilege.rank_answer_vote_up_label"
	RankQuestionVoteDownLabel          = "privilege.rank_question_vote_down_label"
	RankAnswerVoteDownLabel            = "privilege.rank_answer_vote_down_label"
	RankInviteSomeoneToAnswerLabel     = "privilege.rank_invite_someone_to_answer_label"
	RankTagAddLabel                    = "privilege.rank_tag_add_label"
	RankTagEditLabel                   = "privilege.rank_tag_edit_label"
	RankQuestionEditLabel              = "privilege.rank_question_edit_label"
	RankAnswerEditLabel                = "privilege.rank_answer_edit_label"
	RankQuestionEditWithoutReviewLabel = "privilege.rank_question_edit_without_review_label"
	RankAnswerEditWithoutReviewLabel   = "privilege.rank_answer_edit_without_review_label"
	RankQuestionAuditLabel             = "privilege.rank_question_audit_label"
	RankAnswerAuditLabel               = "privilege.rank_answer_audit_label"
	RankTagAuditLabel                  = "privilege.rank_tag_audit_label"
	RankTagEditWithoutReviewLabel      = "privilege.rank_tag_edit_without_review_label"
	RankTagSynonymLabel                = "privilege.rank_tag_synonym_label"
)
